version: '3.6'
services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto-as
    restart: always
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/data/:/mosquitto/data
    networks:
      se4as-network:
        ipv4_address: 173.30.0.100
    ports:
      - "1883:1883"
      - "9001:9001"

networks:
  se4as-network:
    driver: bridge
    ipam:
      config:
        - subnet: 173.30.0.0/16