version: '3.6'
services:
  influxdb:
    image: influxdb:2.4-alpine
    container_name: influxdb
    restart: always
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=se4as_token
      - DOCKER_INFLUXDB_INIT_ORG=se4as
      - DOCKER_INFLUXDB_INIT_BUCKET=stocks
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin123
    ports:
      - '8086:8086'
    volumes:
      - influxdb_data:/var/lib/influxdb
    networks:
      se4as-network:
        ipv4_address: 172.30.0.100

volumes:
  influxdb_data: {}

networks:
  se4as-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16